---
deployment:
  tasks:
   - export DEPLOYPATH=~/public_html/tankbuddy-prod/
   - export ARCHIVEDIRECTORYPATH=~/tankbuddy_deployment_archive/$(date +"%F_%I:%M:%S%p")/
   - /bin/mkdir -p $ARCHIVEDIRECTORYPATH
   - /bin/mv -f $DEPLOYPATH[^.]* $ARCHIVEDIRECTORYPATH
   - /bin/cp -R [^.]* $DEPLOYPATH
   - /usr/bin/git push backup master
